import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    // './sr/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      mobileMax: { min: '320px', max: '767px' },
      tabMax: { min: '320px', max: '980px' }, 
      tabletRange: { min: '767px', max: '1023px' }, 
      tabLg: { min: '320px', max: '1023px' },
      small: "520px",
      mobileStart: "767px",
      mobile: "768px",
      mobileUp: "769px",
      medium: "991px",
      med: "920px",
      laptop: "1024px",
      customSize: '1100px',
      large: "1202px",
      screen: "1280px",
      desktop: "1400px",
      desktoplg: "1580px",
    },
    colors: {
      base: "#42526e",
      hoverbg: "#dfe1e5",
      primary: "#0052CC",
      primaryHover: "#0047b3",
      secondary: "#0065FF",
      white: "#fff",
      borderColor: "#c1c7d0",
      icon: "#636870",
      naviBlue: "#091E42",
      textbase: "#253858",
      lightBlue: "#DEEBFF",
      black: "#000",
      lightBrown: "#FFFAE5",
      lightPurple: "#EAE6FF",
      skyBlue: "#E6FCFF",
      blueBg: "#DEEBFF",
      gray: "#f4f5f7",
      facebook: "#3C5A99",
      twitter: "#60A9DC",
      linkedin: "#016699",
      yellow: "#FFC200"
    },
    fontSize: {
      xx: "12px",
      xsmall: "14px",
      small: "16px",
      md: "20px",
      medium: "22px",
      mdRange: "24px",
      xmd: "25px",
      base: "28px",
      baselg: "32px",
      lg: "36px",
      large: "48px",
    },

    extend: {},
  },
  plugins: [],
}
export default config
